config/routes.rb
Rails.application.routes.draw do

  match "report_test", to: 'reports#report_test', via: 'get'
  match "report_test", to: 'reports#report_test', via: 'post'

  match "month_report", to: 'reports#month_report', via: 'get'
  match "month_report", to: 'reports#month_report', via: 'post'

  match "admin_reports_list",to: 'reports#admin_reports_list', via:'get'
  match "admin_reports_list",to: 'reports#admin_reports_list', via:'post'

  match "user_reports", to: 'reports#user_reports', via: 'get'
  resources :reports

  match "public_user_reports", to:'reports#public_user_reports', via: 'get'
  match "draft_user_reports", to:'reports#draft_user_reports', via: 'get'

  match "admin_users_list",to: 'users#admin_users_list', via:'get'
  devise_for :users, controllers: {sessions: "sessions/sessions",
                                    registrations: "sessions/registrations"}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, :only => [:show]

  root 'users#home'

  get "foobar/hoge"

end

app/views/shared/_report_list.html.erb
<% unless @reports.count == 0%>

  <table class = "Report_list">

    <tr>
      <th>状態</th>
      <th>日報ID</th>
      <th>報告日付</th>
      <th>タイトル</th>
      <th>本文(最初の10文字)</th>
      <th>ユーザーID</th>
      <th>著者名</th>
      <th></th>
      <th></th>
      <th></th>
      <!-- <th></th> -->
    </tr>

    <% @reports.each do |report| %>
      <tr>
        <td><%= report.public_flag? ? "公開" : "下書"%></td>
        <td><%= report.id%></td>
        <td><%= report.reported_date%></td>
        <td><%= report.title %></td>
        <td><%= report.body_text.slice(0,10) %></td>
        <td><%= report.user_id %></td>
        <!--<td><%= User.find(report.user_id).name %></td>-->
        <td><%= report.user.name %></td>

        <td><%= button_to 'Show', report_path(report),method: :get %></td>
        <td><%= button_to 'Edit', edit_report_path(report),method: :get %></td>
        <td><%= button_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>

<% else%>
  日報がありません

<% end%>

app/views/shared/_user_info.html.erb
<h2>
  <%= current_user.name %>
</h2>

<span>
  <%= link_to "Edit my profile" , edit_user_registration_path%>
</span>

<div>
  <p>公開された日報：<b><%=link_to current_user.public_reports_count, public_user_reports_path%></p></b>
  <p>下書き:<b><%= link_to current_user.draft_reports_count, draft_user_reports_path %></p></b>
</div>