config/routes.rb
Rails.application.routes.draw do

  match "report_test", to: 'reports#report_test', via: 'get'
  match "report_test", to: 'reports#report_test', via: 'post'

  match "month_report", to: 'reports#month_report', via: 'get'
  match "month_report", to: 'reports#month_report', via: 'post'

  match "admin_reports_list",to: 'reports#admin_reports_list', via:'get'
  match "admin_reports_list",to: 'reports#admin_reports_list', via:'post'

  match "user_reports", to: 'reports#user_reports', via: 'get'
  resources :reports

  match "public_user_reports", to:'reports#public_user_reports', via: 'get'
  match "draft_user_reports", to:'reports#draft_user_reports', via: 'get'

  match "admin_users_list",to: 'users#admin_users_list', via:'get'
  devise_for :users, controllers: {sessions: "sessions/sessions",
                                    registrations: "sessions/registrations"}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, :only => [:show]

  root 'users#home'

  get "foobar/hoge"

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  #has_many :business_contents

  validates :user_id, presence: true
  validates :title, presence: true

  validates :reported_date, presence: true


  validates :body_text, presence: true,if: [ :public_flag?, :rest_is_nil? ]

  validates :work_start_time, presence: true, if: [ :public_flag?, :rest_is_nil? ]
  validates :work_end_time, presence: true, if: [ :public_flag?, :rest_is_nil? ]


  #validate :report_costom_validate

  def public_flag?
    public_flag == true
  end

  def rest_is_nil?
    rest == nil
  end

  # def rest_is?
  #   rest == nil
  # end
  def report_costom_validate

    if public_flag?
      if rest == "all" || rest == "harf"


      else

        #rest == nil
      end
    else
      #public_flag? == false
    end
  end# def report_costom_validate

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  before_action :correct_or_admin_user,only: [:destroy,:edit,:show]

  before_action :admin_user,only:[:admin_reports_list]

  def new
    @report = Report.new()
  end

  def user_reports
    @reports = current_user.reports
  end

  def public_user_reports
    @reports = current_user.public_reports
  end

  def draft_user_reports
    @reports = current_user.draft_reports
  end

  def admin_reports_list
    if params[:fillterd]
      if params[:user].present?
        user_name = params[:user].to_s
      end
      if params[:year].present?
            year = params[:year].to_s
      end
      if params[:month].present?
            month = params[:month].to_s
      end
      if params[:public_flag].present?
            public_flag = true
      end
      if params[:serch_text].present?
        serch_text = params[:serch_text].to_s
      end
    else
      params[:user] = nil
      params[:year] = nil
      params[:month] = nil
      params[:public_flag] = nil
      params[:serch_text] = nil
    end

    @report = fillterd_report_generator(user_name,year,month,public_flag, serch_text)

  end

  def month_report #月報
    unless params[:year].present?
      params[:year] = Date.today.year
    end
    unless params[:month].present?
      params[:month] = Date.today.month
    end
    @worktime = ApplicationController.helpers.month_report_worktime_calculator(current_user)
    # @resttime = ApplicationController.helpers.month_report_resttime_calculator(current_user)

    @reports = month_report_generator(current_user,params[:year],params[:month])

  end


  def create
    @report = current_user.reports.build(reports_params)

    if @report.save

      respond_to do |format|

        ApplicationController.helpers.send_report(@report.user,@report)

        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      end
    else
    render 'new'
    end

  end

  def edit
   @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(reports_params)

        ApplicationController.helpers.send_report(@report.user,@report)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy
    redirect_to root_url
  end

  def show
    @report = Report.find(params[:id])
  end

  def correct_user
    @report = current_user.reports.find_by(id: params[:id])
    redirect_to root_url if @report.nil?
  end


  private
    def reports_params
      params.require(:report).permit(:title,
                                      :body_text,
                                      :user_id,
                                      :reported_date,
                                      :work_start_time,
                                      :work_end_time,
                                      :rest,
                                      :public_flag)
    end

    # def business_contents_params
    #   params.require(:business_content).permit(:report_id,
    #                                             :content_name)
    # end

    def correct_or_admin_user

      unless current_user.admin?
        @report = current_user.reports.find_by(id: params[:id])
        redirect_to root_url if @report.nil?
      end
    end


    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    #def month_report_generator(user,month)
    def month_report_generator(user,year,month)
      @reports = Report.where(user_id: user, public_flag: true)
      @reports = @reports.where('extract(year from reported_date) = ?', year)
      @reports = @reports.where('extract(month from reported_date) = ?', month)
      @reports #return
    end

    def fillterd_report_generator(user,year,month,public_flag,serch_text)
      @reports = Report.all
      unless user.nil?
        @reports = @reports.where(user_id: user)
      end
      unless year.nil?
        @reports = @reports.where('extract(year from reported_date) = ?', year)
      end
      unless month.nil?
        @reports = @reports.where('extract(month from reported_date) = ?', month)
      end
      unless public_flag.nil?
        @reports = @reports.where(public_flag: true)
      end
      unless serch_text.nil?
        @reports = @reports.where(['body_text LIKE ?', "%#{serch_text}%"])
      end

    end


end

app/helpers/reports_helper.rb
module ReportsHelper
  def send_report(user,report)
    @user = user
    @report = report

    if report.public_flag? && @user.sendto_address != []
      @mail = ReportMail.report_submitted(user,report).deliver
    end
  end

  def month_report_worktime_calculator(user)
    year = Date.today.year
    month = Date.today.month
    @reports = Report.where(user_id: user, public_flag: true)
    @reports = @reports.where('extract(year from reported_date) = ?', year)
    @reports = @reports.where('extract(month from reported_date) = ?', month)
    work_time = calc_month_work_time(@reports)
    @reports = @reports.where('rest = ? OR rest = ? ', "all","harf")
    rest_time = calc_month_rest_time(@reports)

    # return work_time
    return {:work => work_time, :rest => rest_time}
  end
  # def month_report_resttime_calculator(user)
  #   year = Date.today.year
  #   month = Date.today.month
  #   @reports = Report.where(user_id: user, public_flag: true)
  #   @reports = Report.where(user_id: user, public_flag: true)
  #   @reports = @reports.where('extract(year from reported_date) = ?', year)
  #   @reports = @reports.where('extract(month from reported_date) = ?', month)
  #   @reports = @reports.where('rest = ? OR rest = ? ', "all","harf")
  #   rest_time = calc_month_rest_time(@reports)
  #   return rest_time
  # end


  def calc_month_work_time(reports)
    sum_diff_time = 0
    # reports = @reports
    #まず開始時間と終了時間のリストを作成する。
    reports.each do |report|

      starttime = report.work_start_time
      endtime = report.work_end_time

      sum_diff_time += endtime - starttime# this is second
    end

    diff_time_hour = sum_diff_time.divmod(60*60)
    diff_time_min = diff_time_hour[1].divmod(60)

    # return {:hour => hours[0], :minute => mins[0]}
    return{:hour => diff_time_hour[0], :minute => diff_time_min[0]}

  end#def calc_month_work_time


  def calc_month_rest_time(reports)
    rest_time = 0
    # reports = @reports
    #まず開始時間と終了時間のリストを作成する。
    reports.each do |report|

      if report.rest == "all"
        rest_time += 8
      elsif report.rest == "harf"
        rest_time += 4
      else

      end
    end
    return rest_time
  end


end

app/views/reports/_report_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>

  </div>


  <div class = "date_and_rest">
    <div class="date_field">
      <%= f.label "報告日付" %>
      <%= f.date_select(
          :reported_date,
          use_month_numbers: true,
          start_year: Date.today.year - 1,
          default: Date.today(),
          date_separator:    ' / ')%>
    </div>


    <div class="rest_field">
      <%#= f.label "休暇" %>
      <%#= f.radio_button  :rest, { "なし" => nil, "全休" => "all", "半休" => "half" }%>
      <label><%= f.radio_button :rest, :nil %>なし</label>
      <label><%= f.radio_button :rest, "all" %>全休</label>
      <label><%= f.radio_button :rest, "harf" %>半休</label>
    </div>
  </div>

  <div class="work_time_field">
    <div class="time_field">
      <%= f.label "出勤時間"%>
      <%= f.time_select :work_start_time,
                        :default => {:hour => '9', :minute => '00'},
                        :minute_step => 10  %>
    </div>

    <div class="time_field">
      <%= f.label "退勤時間"%>
      <%= f.time_select :work_end_time,
                        :default => {:hour => '18', :minute => '00'},
                        :minute_step => 10  %>
    </div>
  </div>

  <div class="field">
    <%= f.label "題名" %>
    <%= f.text_field :title, placeholder:"日報のタイトル..." %>
  </div>
  <div class="field">
    <%= f.label "本文" %>
    <%= f.text_area :body_text, placeholder:"日報の本文..." %>
  </div>
  <div class="field">
    <%= f.label "公開フラグ" %>
    <%= f.check_box :public_flag, {}, true, false %>
  </div>

  <div class="field">
    <%= %>
  </div>

  <div class="actions">
    <%= f.submit(['save report',]) %>
  </div>
<% end %>

app/views/reports/admin_reports_list.html.erb
<h2>全ての日報一覧</h2>


<div class="admin_report_fillter_field">
<%= form_tag admin_reports_list_path, :method => 'get' do %>
  <div class="fillter_area">
    <div class="fillter_input">
      ユーザーID<br>
      <%= text_field_tag :user, params[:user], :placeholder => "1..."%>
    </div>
    <div class="fillter_input">
      年<br>
      <%= text_field_tag :year, params[:year], :placeholder => "2014..."%>
    </div>

    <div class="fillter_input">
      月<br>
      <%= text_field_tag :month, params[:month], :placeholder => "12..."%>
    </div>
    <div class="check_box_field">
      公開状態 : <%= check_box_tag :public_flag %><br>
    </div>
  </div>

  <div class="serch_text_input">
    本文検索 : <%= text_field_tag :serch_text, params[:serch_text],:placeholder => "abc..." %><br>
  </div>

  <%= submit_tag "更新", :name => 'fillterd' %>

<% end %>
</div>

<%= render 'shared/report_list'%>

app/views/reports/draft_user_reports.html.erb
<h2>下書き一覧</h2>
<%= render 'shared/report_list'%>

app/views/reports/edit.html.erb
<h1>日報の更新</h1>

<%= render 'report_form' %>

<%= link_to 'Back', reports_path%>

app/views/reports/month_report.html.erb
#coding:utf-8


<% display_time = calc_month_work_time(@reports) %>
<% display_rest_time = calc_month_rest_time(@reports) %>

<h2>月報 (<%= "#{params[:year]}" %>年<%= "#{params[:month]}"%>月)</h2>
<div class="month_repory_data">

  今月の労働時間(<%=@worktime[:work][:hour]%>時間<%=@worktime[:work][:minute]%>分)<br>
  表示月の労働時間(<%=display_time[:hour]%>時間<%=display_time[:minute]%>分)<br>
  今月の休憩時間(<%= @worktime[:rest] %>)h 表示月の休憩時間(<%= display_rest_time %>)
</div>

<div class="date_field">
<%= form_tag month_report_path, :mithod => 'get' do %>

  <%= text_field_tag :year, params[:year]%>年
  <%= text_field_tag :month, params[:month]%>月
  <%= submit_tag "更新" %>
<% end %>
</div>

<%= render 'shared/report_list' %>

app/views/reports/new.html.erb
<h1>日報作成</h1>

<%= render 'report_form' %>

<%= link_to 'Back', reports_path%>

app/views/reports/public_user_reports.html.erb
<h2>公開した日報一覧</h2>

<%= render 'shared/report_list'%>

app/views/reports/report_test.html.erb
<h2>レポートの検索とかのテスト領域です</h2>

<%= form_tag report_test_path, :mithod => 'get' do %>

  <%= text_field_tag :hoge, params[:hoge]%>
  <%= submit_tag "更新" %>
<% end %>

<h3>変数に格納してみたやつ <%= @str %> </h3>
<h3>paramsしてみるやつ <%= params[:hoge] %> </h3>


<!-- <%#= form_tag projects_path, :method => 'get' do %> <%#　projects_pathはモデル名で読みかえること %>
  <p>
    <%#= text_field_tag :hoge, params[:hpge] %>
    <%#= submit_tag "Search", :name => nil %>
  </p>
<%# end %> -->

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @report.user.name %>
</p>


<p>
  <b>rest_type</b>
  <%= @report.rest%>

</p>
<p>
  <b>Date:</b>
  <%= @report.reported_date %>
</p>

<p>
  <b>Time:</b>
  <%= @report.work_start_time.strftime('%H:%M') %> ~ <%= @report.work_end_time.strftime('%H:%M') %>
</p>

<p>
  <b>Title:</b>
  <%= @report.title %>
</p>

<p>
  <b>Bodytext:</b>
  <%= @report.body_text %>
</p>

<p>
  <b>公開状態</b>
  <%= @report.public_flag? %>
</p>
<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'home', root_path %>

app/views/reports/user_reports.html.erb
<%= render 'shared/report_list'%>