config/routes.rb
Rails.application.routes.draw do

  match "report_test", to: 'reports#report_test', via: 'get'
  match "report_test", to: 'reports#report_test', via: 'post'

  match "month_report", to: 'reports#month_report', via: 'get'
  match "month_report", to: 'reports#month_report', via: 'post'

  match "admin_reports_list",to: 'reports#admin_reports_list', via:'get'
  match "admin_reports_list",to: 'reports#admin_reports_list', via:'post'

  match "user_reports", to: 'reports#user_reports', via: 'get'
  resources :reports

  match "public_user_reports", to:'reports#public_user_reports', via: 'get'
  match "draft_user_reports", to:'reports#draft_user_reports', via: 'get'

  match "admin_users_list",to: 'users#admin_users_list', via:'get'
  devise_for :users, controllers: {sessions: "sessions/sessions",
                                    registrations: "sessions/registrations"}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  resources :users, :only => [:show]

  root 'users#home'

  get "foobar/hoge"

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixied-top navbar-static-top">
<div class="navbar-inner">

  <div class="container">

    <%= link_to"日報アプリケーション",root_path, id:"logo" %>
    <%#TODO: Pending: sign-in or not signin swiotch link? %>

    <nav>
        <ul class="nav pull-right">

          <% if signed_in? %>

            <li><%= link_to "Home", root_path%></li>

            <% if current_user.admin? %>
              <li><%= link_to "*Users", admin_users_list_path %></li>
              <li><%= link_to "*All Reports", admin_reports_list_path %></li>
            <% end %>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">日報 <b class="caret"></b></a>

              <ul class="dropdown-menu">
                <li><%= link_to "作成", new_report_path%></li>
                <li><%= link_to "一覧",  user_reports_path%></li>

              </ul><!-- #dropdown-menu -->

            </li><!-- fat-menu-->

            <!-- <li><%#= link_to "月報", month_report_path(Date.today.year,Date.today.month) %></li> -->
            <li><%= link_to "月報", month_report_path %></li>

            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>

              <ul class="dropdown-menu">
                <li><%= link_to "Profile", user_path(current_user)%></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>

                <li class="devider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>

              </ul><!-- #dropdown-menu -->

            </li><!-- fat-menu-->
          <% else %>

              <li><%= link_to "Sign in", new_user_session_path%></li>

          <% end %>

        </ul>
    </nav>

  </div><!-- #container -->

</div><!--#navbar-inner-->
</header><!-- /header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DailyReportAppV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header'%>

<div class="container">

  <% flash.each do |key,value|%>
    <%= content_tag(:div, value, class: "alert alert-#{key}")%>
  <% end %>

  <%= yield %>


  <% if Rails.env.development? %>
    <%= debug(params) %>
    <br>
  <% end%>

</div>

</body>

  <%= render 'layouts/footer'%>

</html>